// This file was generated by executing this statement: wav2c bcfire01_48k.wav
extern uint16_t bcfire01_48k_wav[];
#define BCFIRE01_48K_WAV_SAMPLE_RATE 480000
#define BCFIRE01_48K_WAV_BITS_PER_SAMPLE 16
#define BCFIRE01_48K_WAV_NUMBER_OF_SAMPLES 53638
