// This file was generated by executing this statement: wav2c bcfire01.wav
extern uint32_t bcfire01_wav[];
#define BCFIRE01_WAV_SAMPLE_RATE 220500
#define BCFIRE01_WAV_BITS_PER_SAMPLE 16
#define BCFIRE01_WAV_NUMBER_OF_SAMPLES 24640
