// This file was generated by executing this statement: wav2c gameBoyStartup.wav
extern uint16_t gameBoyStartup_wav[];
#define GAMEBOYSTARTUP_WAV_SAMPLE_RATE 480000
#define GAMEBOYSTARTUP_WAV_BITS_PER_SAMPLE 16
#define GAMEBOYSTARTUP_WAV_NUMBER_OF_SAMPLES 105488
