// This file was generated by executing this statement: wav2c gameOver48k.wav
extern uint16_t gameOver48k_wav[];
#define GAMEOVER48K_WAV_SAMPLE_RATE 480000
#define GAMEOVER48K_WAV_BITS_PER_SAMPLE 16
#define GAMEOVER48K_WAV_NUMBER_OF_SAMPLES 156595
