// This file was generated by executing this statement: wav2c gunEmpty48k.wav
extern uint16_t gunEmpty48k_wav[];
#define GUNEMPTY48K_WAV_SAMPLE_RATE 480000
#define GUNEMPTY48K_WAV_BITS_PER_SAMPLE 16
#define GUNEMPTY48K_WAV_NUMBER_OF_SAMPLES 15456
