// This file was generated by executing this statement: wav2c ouch48k.wav
extern uint16_t ouch48k_wav[];
#define OUCH48K_WAV_SAMPLE_RATE 480000
#define OUCH48K_WAV_BITS_PER_SAMPLE 16
#define OUCH48K_WAV_NUMBER_OF_SAMPLES 23467
