// This file was generated by executing this statement: wav2c pacman_beginning_48k.wav
extern uint16_t pacman_beginning_48k_wav[];
#define PACMAN_BEGINNING_48K_WAV_SAMPLE_RATE 480000
#define PACMAN_BEGINNING_48K_WAV_BITS_PER_SAMPLE 16
#define PACMAN_BEGINNING_48K_WAV_NUMBER_OF_SAMPLES 202405
