// This file was generated by executing this statement: wav2c pacmanDeath.wav
extern uint16_t pacmanDeath_wav[];
#define PACMANDEATH_WAV_SAMPLE_RATE 480000
#define PACMANDEATH_WAV_BITS_PER_SAMPLE 16
#define PACMANDEATH_WAV_NUMBER_OF_SAMPLES 82712
