// This file was generated by executing this statement: wav2c powerUp48k.wav
extern uint16_t powerUp48k_wav[];
#define POWERUP48K_WAV_SAMPLE_RATE 480000
#define POWERUP48K_WAV_BITS_PER_SAMPLE 16
#define POWERUP48K_WAV_NUMBER_OF_SAMPLES 60480
