// This file was generated by executing this statement: wav2c screamAndDie48k.wav
extern uint16_t screamAndDie48k_wav[];
#define SCREAMANDDIE48K_WAV_SAMPLE_RATE 480000
#define SCREAMANDDIE48K_WAV_BITS_PER_SAMPLE 16
#define SCREAMANDDIE48K_WAV_NUMBER_OF_SAMPLES 86158
