find_package(Qt5 COMPONENTS Widgets REQUIRED)
find_package(Qt5 COMPONENTS Gui REQUIRED)
find_package(Qt5 COMPONENTS Core REQUIRED)

add_definitions(-DQT_NO_VERSION_TAGGING)

# add_compile_options("-O2")
# add_compile_options("-Wall")
# add_compile_options("-W")
# add_compile_options("-D_REENTRANT")
# add_compile_options("-fPIC")
# add_compile_options("-DQT_DEPRECATED_WARNINGS")
# add_compile_options("-DQT_NO_DEBUG")
# add_compile_options("-DQT_WIDGETS_LIB")
# add_compile_options("-DQT_GUI_LIB")
# add_compile_options("-DQT_CORE_LIB")